language: php
dist: trusty
php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction
  - sh -c '[ "$TRAVIS_PHP_VERSION" == "7.0" ] && composer require satooshi/php-coveralls:~0.6@stable || true'
  - mkdir -p build/logs

script:
  - composer code-style
  - vendor/bin/phpunit --color=always -c phpunit.xml --coverage-clover=build/logs/clover.xml --coverage-text
  - sh -c '[ "$TRAVIS_PHP_VERSION" = "7.0" ] && php vendor/bin/coveralls -v || true'
